package convivio.Convivio;

import java.util.ArrayList;
/**
 * Classe ApresentacaoLocaisUI serve para mostrar ao utilizador 
 * quais os locais disponíveis de um convívio através de uma interface gráfica.
 * @author Pedro Ribeiro e Duarte Carvalho
 */
public class ApresentacaoLocaisUI extends javax.swing.JFrame {
    /**
     * Objecto da classe MainClassUI.
     */
    private MainClassUI importantFrame;
    /**
     * Objecto da classe InsideConvUI.
     */
    private InsideConvUI returnFrame;   
    /**
     * String com o nome do convívio.
     */
    private String nomeConvivio;
    /**
     * Creates new form ApresentacaoLocaisUI.
     * @param importantFrame Um objeto da classe MainClassUI.
     * @param returnFrame Um objecto da classe InsideConvUI.
     * @param nomeConvivio String do nome do convívio cujo os locais quer mostrar.
     * @param order Boolean para verificar se é apresentação dos locais é ordenada, "true" se for para mostrar os locais ordenados por pessoas inscritas.
     */
    public ApresentacaoLocaisUI(MainClassUI importantFrame, InsideConvUI returnFrame, String nomeConvivio, boolean order) {
        this.importantFrame = importantFrame;
        this.returnFrame = returnFrame;
        this.nomeConvivio = nomeConvivio;
        initComponents();  
        if(order){
            populateTextAreaOrdered();
        }else{
            populateTextArea();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infoLocaisTextArea = new javax.swing.JTextArea();
        retornarButton = new javax.swing.JButton();

        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apresentação dos locais do convivio");

        infoLocaisTextArea.setEditable(false);
        infoLocaisTextArea.setColumns(20);
        infoLocaisTextArea.setRows(5);
        jScrollPane1.setViewportView(infoLocaisTextArea);

        retornarButton.setText("Retornar");
        retornarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(retornarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(retornarButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void retornarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        returnFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retornarButtonActionPerformed

    /**
     * Tem como objectivo escrever para a TextArea da janela a descrição dos locais
     * do convívio, caso o convívio não tenha locais apresenta a informação de que 
     * o convívio não possui locais para visitar.
     */
    private void populateTextArea(){
        String infoLocais = "";
        ArrayList<ConvivioDei> listaTotal = importantFrame.getListaConvivios();
        for(ConvivioDei conv : listaTotal){
            if(nomeConvivio.equals(conv.getNome())){
                infoLocais = conv.getInfoLocais();
                break;
            }
        }
        if(infoLocais.equals("")){
            infoLocaisTextArea.setText("Este convívio não tem locais a visitar ainda.");
        }else{
            infoLocaisTextArea.setText(infoLocais);
        }
    }
    
    /**
     * Caso a criação do objecto seja feita para este mostrar a lista por ordem de pessoas
     * inscritas, é chamada este método em vez do "populateTextArea" tendo este o mesmo objectivo.
     * A diferença sendo que este ordena a informação que apresenta, sendo impressos primeiro na TextArea
     * os locais com mais pessoas inscritas.
     */
    private void populateTextAreaOrdered(){
        String infoLocais = "";
        ArrayList<ConvivioDei> listaTotal = importantFrame.getListaConvivios();
        for(ConvivioDei conv : listaTotal){
            if(nomeConvivio.equals(conv.getNome())){
                infoLocais = conv.getInfoLocaisOrdered();
                break;
            }
        }
        if(infoLocais.equals("")){
            infoLocaisTextArea.setText("Este convívio não tem locais a visitar ainda.");
        }else{
            infoLocaisTextArea.setText(infoLocais);
        }
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea infoLocaisTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retornarButton;
    // End of variables declaration//GEN-END:variables
}
