/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convivio.Convivio;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro
 */
public class ClientUI extends javax.swing.JFrame {
    private MainClassUI importantFrame;
    private Pessoa pessoa;
    /**
     * Creates new form ClientUI
     * @param importantFrame
     * @param pessoa
     */
    public ClientUI(MainClassUI importantFrame, Pessoa pessoa) {        
        this.importantFrame = importantFrame;
        this.pessoa = pessoa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        listConviviosButton = new javax.swing.JButton();
        inscreverConvButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem-vindo ");
        jLabel1.setText("Welcome "+pessoa.getNome()+"!");

        listConviviosButton.setText("Listar convívios inscritos");
        listConviviosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listConviviosButtonActionPerformed(evt);
            }
        });

        inscreverConvButton.setText("Inscrever num convívio");

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(listConviviosButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(inscreverConvButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logoutButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(listConviviosButton)
                .addGap(18, 18, 18)
                .addComponent(inscreverConvButton)
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        importantFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void listConviviosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listConviviosButtonActionPerformed
        // TODO add your handling code here:
        boolean open = false;
        ArrayList<ConvivioDei> listaConv = importantFrame.getListaConvivios();
        for(ConvivioDei conv : listaConv){
            if(conv.isPersonRegistered(pessoa)){
                open = true;
                break;
            }
        }
        if(open){
            this.setVisible(false);
            new ListaConviviosUI(importantFrame, this, pessoa).setVisible(true);
        }else{
            int reply = JOptionPane.showConfirmDialog(null, "Não tem nenhum Convivio onde está inscrito, pretende inscrever-se?", "InfoBox: Inscrições", JOptionPane.YES_NO_OPTION);
            if (reply == JOptionPane.YES_OPTION) {         
                this.setVisible(false);
                new InscreverConvivioUI(importantFrame, this, pessoa).setVisible(true);
            }
        }
    }//GEN-LAST:event_listConviviosButtonActionPerformed

    public Pessoa getPessoa() {
        return pessoa;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inscreverConvButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listConviviosButton;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
