package convivio.Convivio;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 * Classe InscreverConvivioUI serve para inscrever um utilizador num determinado
 * convívio através de uma interface gráfica.
 * @author Pedro Ribeiro e Duarte Carvalho
 */
public class InscreverConvivioUI extends javax.swing.JFrame {
    /**
     * Objecto da classe MainClassUI.
     */
    private MainClassUI importantFrame;
    /**
     * Objecto da classe ClientUI.
     */
    private ClientUI clientFrame;
    /**
     * ArraYlist de Strings com o nome dos diferentes convívios.
     */
    private ArrayList<String> convivios;
    /**
     * Objecto da classe Pessoa.
     */
    private Pessoa pessoa;
    /**
     * Creates new form InscreverConvivioUI
     * @param importantFrame Objecto da classe MainClassUI.
     * @param clientFrame Objecto da classe ClientUI.
     * @param pessoa Objecto da classe Pessoa.
     */
    public InscreverConvivioUI(MainClassUI importantFrame, ClientUI clientFrame, Pessoa pessoa) {
        this.importantFrame = importantFrame;
        this.clientFrame = clientFrame;
        this.pessoa = pessoa;
        convivios = new ArrayList<>();
        populateArray();
        initComponents();
        populateTextArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        conviviosComboBox = new javax.swing.JComboBox<>();
        inscreverButton = new javax.swing.JButton();
        cancelarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        locaisTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inscrição num convívio");

        jLabel2.setText("Convívio:");

        conviviosComboBox.setModel(new DefaultComboBoxModel(convivios.toArray()));
        conviviosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conviviosComboBoxActionPerformed(evt);
            }
        });

        inscreverButton.setText("Inscrever");
        inscreverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscreverButtonActionPerformed(evt);
            }
        });

        cancelarButton.setText("Cancelar");
        cancelarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarButtonActionPerformed(evt);
            }
        });

        locaisTextArea.setColumns(20);
        locaisTextArea.setRows(5);
        jScrollPane1.setViewportView(locaisTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(inscreverButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(cancelarButton)
                .addGap(63, 63, 63))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conviviosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(conviviosComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarButton)
                    .addComponent(inscreverButton))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        clientFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarButtonActionPerformed

    private void inscreverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscreverButtonActionPerformed
        // TODO add your handling code here:
        ConvivioDei convivio = null;
        ArrayList<ConvivioDei> listaTotal = importantFrame.getListaConvivios();
        for(ConvivioDei conv : listaTotal){
            if(conviviosComboBox.getSelectedItem().toString().equals(conv.getNome())){
                convivio = conv;
                break;
            }
        }if(convivio != null){
            if(convivio.isPersonRegistered(pessoa)){
                JOptionPane.showMessageDialog(null, "Já está inscrito neste convívio!", "InfoBox: Repetição", JOptionPane.INFORMATION_MESSAGE);
            }else{
                convivio.inscreverPessoa(pessoa);
                JOptionPane.showMessageDialog(null, "Inscrição feita com sucesso!", "InfoBox: Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.setVisible(false);
                clientFrame.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_inscreverButtonActionPerformed

    private void conviviosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conviviosComboBoxActionPerformed
        // TODO add your handling code here:
        populateTextArea();
    }//GEN-LAST:event_conviviosComboBoxActionPerformed

    /**
     * Adiciona o nome dos convívios ao ArrayList.
     */
    public void populateArray(){
        ArrayList<ConvivioDei> listaTotal = importantFrame.getListaConvivios();
        for(ConvivioDei conv : listaTotal){
            convivios.add(conv.getNome());
        }
    } 
    
    /**
     * Imprime no ecrã os locais do convívio selecionado na ComboBox, caso este não tenha
     * locais possíveis de inscrever em é informado que o convívio não tem locais para 
     * apresentar.
     */
    private void populateTextArea(){
        String infoLocais = "";
        ArrayList<ConvivioDei> listaTotal = importantFrame.getListaConvivios();
        for(ConvivioDei conv : listaTotal){
            if(conviviosComboBox.getSelectedItem().toString().equals(conv.getNome())){
                infoLocais = conv.getInfoLocais();
            }
        }
        if(infoLocais.equals("")){
            locaisTextArea.setText("Este convívio não tem locais a visitar ainda.");
        }else{
            locaisTextArea.setText(infoLocais);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarButton;
    private javax.swing.JComboBox<String> conviviosComboBox;
    private javax.swing.JButton inscreverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea locaisTextArea;
    // End of variables declaration//GEN-END:variables
}
