package convivio.Convivio;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 * Classe MainClassUI primeiro menu que aparece para a criação de utilizadores 
 * e login.
 * @author Pedro Ribeiro e Duarte Carvalho
 */
public class MainClassUI extends javax.swing.JFrame {
    /**
     * ArrayList de convívios que estão disponíveis para o utilizador.
     */
    private ArrayList<ConvivioDei> listaConvivios;
    /**
     * ArrayList de pessoas que têm "conta" no programa.
     */
    private ArrayList<Pessoa> listaPessoas;
    /**
     * Creates new form MainClassUI
     */
    public MainClassUI() {
        initComponents();
        this.listaConvivios = new ArrayList<>();
        this.listaPessoas = new ArrayList<>();
        readFichPessoas();
        readFichConvivios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        criarUserButton = new javax.swing.JButton();
        fecharButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Convívios do DEI");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        criarUserButton.setText("Criar um novo utilizador");
        criarUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarUserButtonActionPerformed(evt);
            }
        });

        fecharButton.setText("Fechar");
        fecharButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fecharButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(criarUserButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fecharButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addComponent(loginButton)
                .addGap(18, 18, 18)
                .addComponent(criarUserButton)
                .addGap(18, 18, 18)
                .addComponent(fecharButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void criarUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarUserButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new NewUserUI(this).setVisible(true);
    }//GEN-LAST:event_criarUserButtonActionPerformed

    private void fecharButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fecharButtonActionPerformed
        // TODO add your handling code here:
        writeFichPessoas();
        writeFichConv();
        this.setVisible(false);
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_fecharButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginUI(this).setVisible(true);
    }//GEN-LAST:event_loginButtonActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==KeyEvent.VK_ENTER){
            getRootPane().setDefaultButton(loginButton);
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     *
     * @return Arraylist de pessoas.
     */
    public ArrayList<Pessoa> getListaPessoas() {
        return listaPessoas;
    }

    /**
     * Adiciona uma pessoa à lista de pessoas com "conta" no programa.
     * @param p Objecto da classe Pessoa.
     */
    public void addPessoa(Pessoa p){
        listaPessoas.add(p);
    }
    
    /**
     * Adiciona um convívio à lista de convívios disponíveis ao utilizador.
     * @param c Objecto da classe ConvivioDei
     */
    public void addConvivio(ConvivioDei c){
        listaConvivios.add(c);
    }
    
    /**
     * Devolve o objecto da Classe pessoa que tenha o nome passado por argumento, devolve
     * null caso náo encontre ninguém.
     * @param s String com o nome de uma pessoa.
     * @return Objecto da classe Pessoa.
     */
    public Pessoa searchPessoa(String s){
        for(Pessoa p : listaPessoas){
            if(s.equals(p.getNome())){
                return p;
            }
        }
        return null;
    }
    
    /**
     * Verifica se a password escrita pelo utilizador é a password da "conta".
     * Caso seja devolve "true", "false" caso contrário.
     * @param p Objecto da classe Pessoa.
     * @param password String com a palavra-passe da pessoa.
     * @return Boolean.
     */
    public boolean isPasswordCorrect(Pessoa p, String password){
        if(password.equals(p.getPassword())){
            return true;
        }else{
            return false;
        }
    }

    /**
     *
     * @return ArrayList de convívios.
     */
    public ArrayList<ConvivioDei> getListaConvivios() {
        return listaConvivios;
    }
    
    /**
     * Devolve o objecto da classe ConvivioDei que tem o nome passado como 
     * argumento.
     * @param nome String com o nome do convívio.
     * @return Objecto da classe ConvivioDei.
     */
    public ConvivioDei getConvivio(String nome){
        for(ConvivioDei cv : listaConvivios){
            if(cv.getNome().equals(nome)){
                return cv;
            }
        }
        return null;
    }
    
    /**
     * Inscreve uma pessoa num local de um determinado convívio.
     * Devolve inteiro, 1 se for realizada com sucesso, -1 se não for possível 
     * inscrever uma pessoa no local.
     * @param c Objecto da classe ConvivioDei.
     * @param p Objecto da classe Pessoa.
     * @param l Objecto da classe Local.
     * @return Inteiro.
     */
    public int inscreverEmLocal(ConvivioDei c, Pessoa p, Local l){
        int index = listaConvivios.indexOf(c);
        int flag = listaConvivios.get(index).inscreverEmLocal(p,l);
        return flag;
    }
    
    /**
     * Desinscreve uma pessoa de um local de um determinado convívio.
     * @param c Objecto da classe ConvivioDei.
     * @param p Objecto da classe Pessoa.
     * @param l Objecto da classe Local.
     */
    public void desisncreverDeLocal(ConvivioDei c, Pessoa p, Local l){
        int index = listaConvivios.indexOf(c);
        listaConvivios.get(index).desinscreverDeLocal(p.getNome(), l);
    }
    
    /**
     * Verifica se já exite algum convívio com o nome passado como parametro, devolve
     * true se já existir.
     * @param s String com o nome de um convívio.
     * @return 
     */
    public boolean hasSameNameConvivio(String s){
        for(ConvivioDei conv : listaConvivios){
            if(conv.getNome().equals(s)){
                return true;
            }
        }
        return false;
    }
    
    /**
     * Adiciona um local à lista de locais de um convívio.
     * @param nome String com o nome do convívio ao qual queremos adicionar o local.
     * @param l Objecto local que queremos adicionar ao convivio.
     */
    public void adicionarLocalAConvivio(String nome, Local l){
        for(ConvivioDei conv : listaConvivios){
            if(conv.getNome().equals(nome)){
                conv.adicionarLocal(l);
                break;
            }
        }
    }
  
    /**
     * Lê do ficheiro de text das pessoas inscritas no programa.
     */
    public void lerTxtPessoas(){
        try{
            File f = new File("Pessoas.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String aux;
            String [] parts;            
            while((aux=br.readLine())!=null){
                parts = aux.split("-");
                if(parts[0].compareTo("A")==0){
                    Aluno a = new Aluno(parts[1],parts[2],parts[3],parts[4]);
                    listaPessoas.add(a);
                }
                else if(parts[0].compareTo("P")==0){
                    Professor p = new Professor(parts[1],parts[2],parts[3],parts[4]);
                    listaPessoas.add(p);
                }
                else if(parts[0].compareTo("F")==0){
                    Funcionario fc = new Funcionario(parts[1],parts[2],parts[3],parts[4]);
                    listaPessoas.add(fc);
                }
            }
            br.close();
        }
        catch (IOException ex) {
            System.out.println(ex);
        }
    }
    
    /**
     * Lê o ficheiro de objectos das pessoas inscritas.
     */
    public void readFichPessoas(){
        try{
            File f = new File("Pessoas.obj");
            FileInputStream fis = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(fis);
            listaPessoas = (ArrayList<Pessoa>)ois.readObject();
            ois.close();
        }
        catch (FileNotFoundException ex) {
            lerTxtPessoas();
            writeFichPessoas();
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }
    
    /**
     * Escreve para o ficheiro de objectos as pessoas inscritas.
     */
    public void writeFichPessoas(){
        try{
            File f = new File("Pessoas.obj");
            FileOutputStream fos = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fos);            
            oos.writeObject(listaPessoas);
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }
    
    /**
     * Lê do ficheiro de texto os convivios disponiveis.
     */
    public void lerTxtConvivioDei(){
        try{
            File f = new File("ConvivioDei.txt");
            FileReader fr = new FileReader(f);
            BufferedReader br = new BufferedReader(fr);
            String aux,aux2;
            String [] parts;
            String [] partsPessoa;
            String [] partsLocal;
            ArrayList<Pessoa> pessoasIns = new ArrayList();
            ArrayList<Local> locaisIns = new ArrayList();
            ArrayList<String> desportos = new ArrayList();
            
            while((aux=br.readLine())!=null){
                parts = aux.split("-");
                String []helper = parts[1].split(";");
                for(int i=0;i<helper.length;i++){   
                    Pessoa p = searchPessoa(helper[i]);
                    if(p!=null){
                        pessoasIns.add(searchPessoa(helper[i]));   
                    }
                }
                String []helper2= parts[2].split(";");
                for(int i=0;i<helper2.length;i++){
                    partsLocal = helper2[i].split(",");
                    if(partsLocal[0].compareTo("AD")==0){
                        desportos.clear();
                        String []ajudante = partsLocal[4].split("/");
                        for(int j=0;j<ajudante.length;j++){
                            desportos.add(ajudante[i]);
                        }
                        AreaDesportiva ad = new AreaDesportiva(partsLocal[1],Double.parseDouble(partsLocal[2]),Double.parseDouble(partsLocal[3]),desportos);
                        locaisIns.add(ad);
                    }
                    else if(partsLocal[0].compareTo("B")==0){
                        Bar b = new Bar(partsLocal[1],Integer.parseInt(partsLocal[2]),Double.parseDouble(partsLocal[3]),Double.parseDouble(partsLocal[4]),Double.parseDouble(partsLocal[5]));
                        locaisIns.add(b);
                    }
                    else if(partsLocal[0].compareTo("E")==0){
                        Exposicao ex = new Exposicao(partsLocal[1],partsLocal[2],Double.parseDouble(partsLocal[3]),Double.parseDouble(partsLocal[4]),Double.parseDouble(partsLocal[5]));
                        locaisIns.add(ex);
                    }
                    else if(partsLocal[0].compareTo("J")==0){
                        Jardim j = new Jardim(partsLocal[1],Double.parseDouble(partsLocal[2]),Double.parseDouble(partsLocal[3]),Double.parseDouble(partsLocal[4]));
                        locaisIns.add(j);   
                    }
                }   
                ConvivioDei cd = new ConvivioDei(parts[0],pessoasIns,locaisIns);
                listaConvivios.add(cd);
            }
            br.close();
        }
        catch (FileNotFoundException ex) {
            System.out.println(ex);
        }
        catch (IOException ex) {
            System.out.println(ex);
        }
    }
    
    /**
     * Lê o ficheiro de objectos dos convívios.
     */
    public void readFichConvivios(){        
        try{
            File f = new File("ConvivioDei.obj");
            FileInputStream fis = new FileInputStream(f);
            ObjectInputStream ois = new ObjectInputStream(fis);
            listaConvivios = (ArrayList<ConvivioDei>)ois.readObject();
            ois.close();
        }
        catch (FileNotFoundException ex) {
            lerTxtConvivioDei();
            writeFichConv();
        } catch (IOException ex) {
            System.out.println(ex);
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
        }
    }
    
    /**
     * Escreve para o ficheiro de objectos os convívios.
     */
    public void writeFichConv(){
        try{
            File f = new File("ConvivioDei.obj");
            FileOutputStream fos = new FileOutputStream(f);
            ObjectOutputStream oos = new ObjectOutputStream(fos);            
            oos.writeObject(listaConvivios);
        } catch (FileNotFoundException ex) {
            System.out.println(ex);
        } catch (IOException ex) {
            System.out.println(ex);
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainClassUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainClassUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainClassUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainClassUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new MainClassUI().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarUserButton;
    private javax.swing.JButton fecharButton;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
