/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package convivio.Convivio;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author pedro
 */
public class SelecaoLocaisUI extends javax.swing.JFrame {
    private MainClassUI importantFrame;
    private InsideConvUI returnFrame;    
    private String nomeConvivio;
    private ArrayList<String> locais;
    private Pessoa pessoa;
    /**
     * Creates new form SelecaoLocaisUI
     */
    public SelecaoLocaisUI(MainClassUI importantFrame, InsideConvUI returnFrame, String nomeConvivio, Pessoa pessoa) {
        this.importantFrame = importantFrame;
        this.returnFrame = returnFrame;
        this.nomeConvivio = nomeConvivio;
        this.pessoa = pessoa;
        this.locais = new ArrayList<>();
        populateArray();
        initComponents();        
        populateList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        todosLocaisComboBox = new javax.swing.JComboBox<>();
        inscreverButton = new javax.swing.JButton();
        desinscreverButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        retornarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleção de Locais a Visitar");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        todosLocaisComboBox.setModel(new DefaultComboBoxModel(locais.toArray()));

        inscreverButton.setText("Inscrever");
        inscreverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscreverButtonActionPerformed(evt);
            }
        });

        desinscreverButton.setText("Desinscrever");
        desinscreverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desinscreverButtonActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Locais inscritos");

        retornarButton.setText("Retornar");
        retornarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retornarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retornarButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(todosLocaisComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inscreverButton, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(desinscreverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(todosLocaisComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inscreverButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desinscreverButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(retornarButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void retornarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retornarButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        returnFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_retornarButtonActionPerformed

    private void inscreverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscreverButtonActionPerformed
        // TODO add your handling code here:
        ConvivioDei convivio = importantFrame.getConvivio(nomeConvivio);
        ArrayList<Local> listaTotal = convivio.getListaLocais();
        Local l = null;
        for(Local local : listaTotal){
            if(local.getNome().equals(todosLocaisComboBox.getSelectedItem().toString())){
                l = local;
                break;
            }
        }
        if(l != null){
            if(jList1.getModel().getSize() == 5){
                JOptionPane.showMessageDialog(null, "Só se pode inscrever em 5 locais!", "InfoBox: Excesso de locais", JOptionPane.INFORMATION_MESSAGE);
            }else{   
                boolean isAlreadyRegistered = false;
                ListModel model = jList1.getModel();
                for(int i=0; i < model.getSize(); i++){
                     if(model.getElementAt(i).equals(todosLocaisComboBox.getSelectedItem().toString())){
                         isAlreadyRegistered = true;
                         break;
                     }  
                }
                if(!isAlreadyRegistered){
                    int flag = importantFrame.inscreverEmLocal(convivio, pessoa, l);
                    if(flag == 2){
                        JOptionPane.showMessageDialog(null, "A inscrição no bar foi feita com sucesso e foi adicionado à GuestList!", "InfoBox: Inscricao", JOptionPane.INFORMATION_MESSAGE);
                    }else if(flag == 1){
                        JOptionPane.showMessageDialog(null, "A inscrição foi feita com sucesso!", "InfoBox: Inscricao", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                        JOptionPane.showMessageDialog(null, "Não se consegui inscrever pois estava lotado!", "InfoBox: Inscricao", JOptionPane.INFORMATION_MESSAGE);
                    }
                    populateList();
                }else{
                    JOptionPane.showMessageDialog(null, "Já se inscreveu nessa opção!", "InfoBox: Repetição de locais", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }        
    }//GEN-LAST:event_inscreverButtonActionPerformed

    private void desinscreverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desinscreverButtonActionPerformed
        // TODO add your handling code here:
        ConvivioDei convivio = importantFrame.getConvivio(nomeConvivio);
        ArrayList<Local> listaTotal = convivio.getListaLocais();
        Local l = null;
        for(Local local : listaTotal){
            if(local.getNome().equals(jList1.getSelectedValue())){
                l = local;
                break;
            }
        }
        if(l != null){
            importantFrame.desisncreverDeLocal(convivio, pessoa, l);
            populateList();
        }
    }//GEN-LAST:event_desinscreverButtonActionPerformed

    private void populateArray(){
        ConvivioDei convivio = importantFrame.getConvivio(nomeConvivio);
        ArrayList<Local> listaTotal = convivio.getListaLocais();
        for(Local local : listaTotal){
            locais.add(local.getNome());
        }
    }
    
    private void populateList(){
        DefaultListModel dlm = new DefaultListModel();
        ConvivioDei convivio = importantFrame.getConvivio(nomeConvivio);
        ArrayList<Inscricao> inscricoes = convivio.getInscricoes();
        for(Inscricao ins : inscricoes){
            if(pessoa.getNome().equals(ins.getNomePessoa())){
                dlm.addElement(ins.getNomeLocal());
            }
        }
        jList1.setModel(dlm);        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton desinscreverButton;
    private javax.swing.JButton inscreverButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retornarButton;
    private javax.swing.JComboBox<String> todosLocaisComboBox;
    // End of variables declaration//GEN-END:variables
}
